"""Add unique fields 2

Revision ID: 07e3b7e3d524
Revises: af7c7d1e31ec
Create Date: 2024-11-19 16:45:57.787287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e3b7e3d524'
down_revision: Union[str, None] = 'af7c7d1e31ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_shop_user_id'), 'shop', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_shop_user_id'), 'shop', type_='unique')
    # ### end Alembic commands ###
