"""Fixed url in shop field

Revision ID: 4587dc2ce3fe
Revises: 2b0155b72af7
Create Date: 2024-11-07 14:41:14.357275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4587dc2ce3fe'
down_revision: Union[str, None] = '2b0155b72af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'url')
    # ### end Alembic commands ###
