"""Add unique fields

Revision ID: af7c7d1e31ec
Revises: 3a47bae51d87
Create Date: 2024-11-19 16:33:09.374608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7c7d1e31ec'
down_revision: Union[str, None] = '3a47bae51d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_product_name'), 'product', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product_name'), 'product', type_='unique')
    # ### end Alembic commands ###
