"""Fixed enum congig

Revision ID: 2b0155b72af7
Revises: b3e7dc604eed
Create Date: 2024-10-31 17:17:35.869802

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2b0155b72af7'
down_revision: Union[str, None] = 'b3e7dc604eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
order_status = sa.Enum('CONFIRMED', 'ASSEMBLED', 'SENT', 'DELIVERED', 'CANCELED', 'INPROGRES', name='orderstatus')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', order_status, server_default='INPROGRES', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_table('shoppingcart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_shoppingcart_product_id_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name=op.f('fk_shoppingcart_user_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shoppingcart'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingcart')
    op.drop_table('order')
    order_status.drop(op.get_bind())
    # ### end Alembic commands ###
