"""Add unique field

Revision ID: 3a47bae51d87
Revises: 1180909d382a
Create Date: 2024-11-19 16:07:21.360527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a47bae51d87'
down_revision: Union[str, None] = '1180909d382a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_parametr_name'), 'parametr', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_parametr_name'), 'parametr', type_='unique')
    # ### end Alembic commands ###
